version: "3.3"

services:
    db:
        image: "postgres:9.6"
        restart: always
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_PASSWORD: b245005e8b3df99ac373f72240ba14df
        volumes:
            - /home/sebastian/temp/pgdata:/var/lib/postgresql/data/pgdata

    api:
        build: ./api
        restart: always

    web:
        build: ./web
        restart: always
        ports:
            - "8080:80"
