version: "3.3"

services:
    db:
        image: "postgres:9.6"
        restart: always
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_PASSWORD: b245005e8b3df99ac373f72240ba14df
        volumes:
            - ~/temp/pgdata:/var/lib/postgresql/data/pgdata
        networks:
            - dbnet

    api:
        build: ./api
        restart: always
        networks:
            - apinet
            - dbnet

    web:
        build: ./web
        restart: always
        networks:
            - webnet
            - apinet
        ports:
            - "8080:80"

networks:
    dbnet:
        internal: true
    apinet:
        internal: true
    webnet:
        internal: false
